In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np
from data import CIFAR10
from ff import FF

In [2]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

In [3]:
batch_size = 4

In [4]:
trainset = torchvision.datasets.CIFAR10(root='./datasets', train=True,
                                        download=True, transform=transform)

Files already downloaded and verified


In [5]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

In [6]:
testset = torchvision.datasets.CIFAR10(root='./datasets', train=False,
                                       download=True, transform=transform)

Files already downloaded and verified


In [7]:
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

# Inference

In [8]:
config = {
    "in_dims": [3072, 3072],
    "out_dims": [3072, 3072],
    "epochs": 4,
    "threshold": 1.5
}
num_layers = 2

In [9]:
model = FF(num_layers, config, torch.optim.Adam)

In [10]:
model.train()

FF()

In [11]:
x = iter(trainloader)

In [12]:
x, y = next(x)

In [13]:
new_x, new_y = CIFAR10.overlay_y_on_x(x, y)

In [14]:
model(new_x)

torch.Size([4, 3072])
tensor([0.0001, 0.0001, 0.0001, 0.0001], grad_fn=<MeanBackward1>)
torch.Size([4, 3072])
tensor([0.0001, 0.0001, 0.0001, 0.0001], grad_fn=<MeanBackward1>)


tensor([0.0002, 0.0002, 0.0002, 0.0002], grad_fn=<AddBackward0>)

# Training

In [15]:
trainset = torchvision.datasets.CIFAR10(root='./datasets', train=True,
                                        download=True, transform=transform)

Files already downloaded and verified


In [16]:
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

In [21]:
model.train()
for i, (x, y) in enumerate(trainloader):
    
    x_pos, _ =  CIFAR10.overlay_y_on_x(x, y)
    false_y = torch.randint(0, 10, (x.shape[0],))
    x_neg, _ = CIFAR10.overlay_y_on_x(x, false_y)
    losses = model(x_pos, x_neg)
    print(losses)

0.950603
0.943953
0.9349706
0.9205848
0.9278462
0.87681806
0.8407248
0.88461375
0.76245344
0.81595945
0.8767848
0.7442508
0.80894935
0.79518664
0.80952275
0.8305385
0.8147986
0.7591651
0.7532683
0.84610057
0.81066287
0.7875005
0.7887848
0.7958966
0.7614354
0.74856603
0.811008
0.779246
0.82085335
0.7566781
0.7251791
0.74040264
0.72135925
0.7518133
0.7381878
0.7568997
0.7721082
0.79780674
0.73032856
0.7198066
0.7110294
0.78091025
0.7618953
0.73737335
0.7573011
0.70215094
0.72947335
0.7776158
0.7355968
0.7448491
0.7474524
0.75043774
0.74044687
0.75440204
0.7209739
0.7123635
0.7292723
0.7366022
0.7369691
0.69742835
0.72892314
0.71825814
0.7544435
0.7089061
0.7385582
0.7159186
0.7243202
0.72447824
0.739874
0.71977174
0.7202194
0.76611745
0.7774634
0.74312603
0.7436273
0.7509624
0.7627218
0.72501063
0.7333901
0.74117035
0.7415739
0.73069996
0.7420896
0.7295407
0.73329115
0.7121377
0.7008207
0.73504794
0.7468398
0.72749114
0.7163427
0.70369244
0.7218575
0.7102656
0.72839487
0.7163131
0.729534

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x115236670>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/deeplearning/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/deeplearning/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1442, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/deeplearning/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/deeplearning/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/deeplearning/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeou

KeyboardInterrupt: 